indicators:
  - key: "at_birth_vaccines"
    isMultiResult: true
    grouping: "report_group_header_vaccination_activity"
    description: "Grouped query for number of children aged 0-59months who received particular vaccines"
    indicatorQuery: "SELECT vaccines.name,
                            CASE
                                WHEN round(julianday('now') - julianday(ec_client.dob)) <= 1 THEN '0_24hrs'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= 2 AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= 59 THEN '2_59days'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (2 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (6 * 30.436875) THEN '2_6mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (7 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (11 * 30.436875) THEN '7_11mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (12 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (17 * 30.436875) THEN '12_17mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (18 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (23 * 30.436875) THEN '18_23mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (24 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (59 * 30.436875) THEN '24_59mnths'
                                ELSE 'Null'
                                END age,
                            count(*)
                     FROM vaccines
                              INNER JOIN ec_client
                                         ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')
                     GROUP BY vaccines.name, age"
    expectedIndicators:
      - "at_birth_vaccines_bcg_0_24hrs"
      - "at_birth_vaccines_bcg_2_59days"
      - "at_birth_vaccines_hep_b_0_0_24hrs"
      - "at_birth_vaccines_hep_b_0_2_59days"
      - "at_birth_vaccines_pcv_2_2_6mnths"
      - "at_birth_vaccines_pcv_2_7_11mnths"
      - "at_birth_vaccines_pcv_2_12_17mnths"
      - "at_birth_vaccines_pcv_2_18_23mnths"
      - "at_birth_vaccines_pcv_2_24_59mnths"
      - "at_birth_vaccines_pcv_3_7_11mnths"
      - "at_birth_vaccines_pcv_3_12_17mnths"
      - "at_birth_vaccines_pcv_3_18_23mnths"
      - "at_birth_vaccines_pcv_3_24_59mnths"
      - "at_birth_vaccines_mr_1_12_17mnths"
      - "at_birth_vaccines_mr_1_18_23mnths"
      - "at_birth_vaccines_mr_1_24_59mnths"
      - "at_birth_vaccines_mr_2_18_23mnths"
      - "at_birth_vaccines_mr_2_24_59mnths"
      - "at_birth_vaccines_dtp_4_18_23mnths"
      - "at_birth_vaccines_dtp_4_24_59mnths"

  - key: "penta1_grp"
    isMultiResult: true
    grouping: "report_group_header_vaccination_activity"
    description: "Grouped query for number of children aged 0-59months who received ipv_1, pcv_1 and penta_1 vaccines"
    indicatorQuery: "SELECT 'penta1'                       as penta1,
                            CASE
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (2 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (6 * 30.436875) THEN '2_6mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (7 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (11 * 30.436875) THEN '7_11mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (12 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (17 * 30.436875) THEN '12_17mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (18 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (23 * 30.436875) THEN '18_23mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (24 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (59 * 30.436875) THEN '24_59mnths'
                                ELSE 'Null'
                                END                            age,
                            (SELECT count(*)
                             FROM vaccines
                             WHERE vaccines.name = 'ipv_1'
                                OR vaccines.name = 'penta_1'
                                OR vaccines.name = 'pcv_1') as count
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                        AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')
                     GROUP BY age;"
    expectedIndicators:
      - "penta1_grp_penta1_2_6mnths"
      - "penta1_grp_penta1_7_11mnths"
      - "penta1_grp_penta1_12_17mnths"
      - "penta1_grp_penta1_18_23mnths"
      - "penta1_grp_penta1_24_59mnths"

  - key: "penta2_grp"
    isMultiResult: true
    grouping: "report_group_header_vaccination_activity"
    description: "Grouped query for number of children aged 0-59months who received ipv_2 and penta_2 vaccines"
    indicatorQuery: "SELECT 'penta2'                          as penta2,
                            CASE
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (2 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (6 * 30.436875) THEN '2_6mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (7 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (11 * 30.436875) THEN '7_11mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (12 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (17 * 30.436875) THEN '12_17mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (18 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (23 * 30.436875) THEN '18_23mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (24 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (59 * 30.436875) THEN '24_59mnths'
                                ELSE 'Null'
                                END                              age,
                            (SELECT count(*)
                             FROM vaccines
                             WHERE vaccines.name = 'ipv_2'
                                OR vaccines.name = 'penta_2') as count
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')
                     GROUP BY age;"
    expectedIndicators:
      - "penta2_grp_penta2_2_6mnths"
      - "penta2_grp_penta2_7_11mnths"
      - "penta2_grp_penta2_12_17mnths"
      - "penta2_grp_penta2_18_23mnths"
      - "penta2_grp_penta2_24_59mnths"

  - key: "penta3_grp"
    isMultiResult: true
    grouping: "report_group_header_vaccination_activity"
    description: "Grouped query for number of children aged 0-59months who received ipv_1 and penta_3 vaccines"
    indicatorQuery: "SELECT 'penta3'                          as penta3,
                            CASE
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (2 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (6 * 30.436875) THEN '2_6mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (7 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (11 * 30.436875) THEN '7_11mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (12 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (17 * 30.436875) THEN '12_17mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (18 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (23 * 30.436875) THEN '18_23mnths'
                                WHEN round(julianday('now') - julianday(ec_client.dob)) >= (24 * 30.436875) AND
                                     round(julianday('now') - julianday(ec_client.dob)) <= (59 * 30.436875) THEN '24_59mnths'
                                ELSE 'Null'
                                END                              age,
                            (SELECT count(*)
                             FROM vaccines
                             WHERE vaccines.name = 'opv_1'
                                OR vaccines.name = 'penta_3') as count
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')
                     GROUP BY age;"
    expectedIndicators:
      - "penta3_grp_penta3_2_6mnths"
      - "penta3_grp_penta3_7_11mnths"
      - "penta3_grp_penta3_12_17mnths"
      - "penta3_grp_penta3_18_23mnths"
      - "penta3_grp_penta3_24_59mnths"

  - key: "bcg_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received BCG vaccine at the facility"
    indicatorQuery: "SELECT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND vaccines.name = 'bcg'
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "hepb_0_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received Hep B 0 vaccine at the facility"
    indicatorQuery: "SELECT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND vaccines.name = 'hep_b_0'
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "penta1_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received Penta1, IPV1 and PCV1 vaccines"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'ipv_1' OR vaccines.name = 'penta_1' OR vaccines.name ='pcv_1')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "penta2_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received Penta2 and IPV2 vaccines"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'penta_2' OR vaccines.name ='ipv_2')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"
  - key: "pcv2_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received  PCV2  vaccines"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'pcv_2')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "penta3_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received Penta 3 and OPV1  vaccines"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'penta_3' OR vaccines.name ='opv_1')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "pcv3_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received  PCV3 vaccines"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'pcv_3')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "mr1_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received  MR1vaccine"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'mr_1')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "mr2_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received  MR2 vaccine"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'mr_2')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"

  - key: "dtp4_total"
    grouping: "report_group_header_vaccination_activity"
    description: "Total number of children of all ages who received DTP4 vaccine"
    indicatorQuery: "SELECT DISTINCT count(1)
                     FROM vaccines
                              INNER JOIN ec_client ON vaccines.base_entity_id = ec_client.base_entity_id
                     WHERE ec_client.is_closed != 1
                       AND (vaccines.name = 'dtp_4')
                       AND strftime('%Y-%m-%d', '%s') = date(vaccines.date / 1000, 'unixepoch', 'localtime')"