---
group: yellow_attention_flag
fields:

  - template: "Age: {age}"
    relevance: "age <= 17 || age >= 35"

  - template: "Gravida: {gravida}"
    relevance: "gravida >= 5"

  - template: "Parity: {parity}"
    relevance: "parity >= 5"

  - template: "Past pregnancy problems: {prev_preg_comps_value}"
    relevance: "!prev_preg_comps.isEmpty() && !prev_preg_comps.contains('none')"

  - template: "Past alcohol / substances used: {substances_used_value}"
    relevance: "!substances_used.isEmpty() && !substances_used.contains('none')"

  - template: "Pre-eclampsia risk"
    relevance: "preeclampsia_risk == 1"

  - template: "Diabetes risk"
    relevance: "gdm_risk == 1"

  - template: "Surgeries: {surgeries_value}"
    relevance: "!surgeries.isEmpty() && !surgeries.contains('none')"

  - template: "Chronic health conditions: {health_conditions_value}"
    relevance: "!health_conditions.isEmpty() && !health_conditions.contains('none')"

  - template: "High daily consumption of caffeine"
    relevance: "!caffeine_intake.isEmpty() && !caffeine_intake.contains('none')"

  - template: "Second-hand exposure to tobacco smoke"
    relevance: "shs_exposure == 'yes'"

  - template: "Persistent physiological symptoms: {phys_symptoms_persist_value}"
    relevance: "!phys_symptoms_persist.isEmpty() && !phys_symptoms_persist.contains('none')"

  - template: "Reduced or no fetal movement perceived by woman"
    relevance: "mat_percept_fetal_move != '' && mat_percept_fetal_move != 'normal_fetal_move'"

  - template: "Weight category: {weight_cat_value}"
    relevance: "weight_cat != '' && (weight_cat == 'underweight' || weight_cat == 'overweight' || weight_cat == 'obese')"

  - template: "Abnormal breast exam: {breast_exam_abnormal_value}"
    relevance: "!breast_exam_abnormal.contains('none') && !breast_exam_abnormal.isEmpty()"

  - template: "Abnormal abdominal exam: {abdominal_exam_abnormal_value}"
    relevance: "!abdominal_exam_abnormal.contains('none') && !abdominal_exam_abnormal.isEmpty()"

  - template: "Abnormal pelvic exam: {pelvic_exam_abnormal_value}"
    relevance: "!pelvic_exam_abnormal.contains('none') && !pelvic_exam_abnormal.isEmpty()"

  - template: "Oedema present"
    relevance: "oedema == 'yes'"

  - template: "Rh factor negative"
    relevance: "rh_factor == 'negative'"
---
group: red_attention_flag
fields:

  - template: "Danger sign(s): {danger_signs_value}"
    relevance: "!danger_signs.isEmpty() && !danger_signs.contains('danger_none')"

  - template: "Occupation: Informal employment (sex worker)"
    relevance: "occupation.contains('informal_employment_sex_worker')"

  - template: "No. of pregnancies lost/ended: {miscarriages_abortions}"
    relevance: "miscarriages_abortions >= 2"

  - template: "No. of stillbirths: {stillbirths}"
    relevance: "{stillbirths} >= 1"

  - template: "No. of C-sections: {c_sections}"
    relevance: "{c_sections} >= 1"

  - template: "Allergies: {allergies_value}"
    relevance: "!allergies.isEmpty() && !allergies.contains('none')"

  - template: "Tobacco user or recently quit"
    relevance: "tobacco_user == 'yes' ||  tobacco_user == 'recently_quit'"

  - template: "Woman and her partner(s) do not use condoms"
    relevance: "condom_use == 'no'"

  - template: "Alcohol / substances currently using: {alcohol_substance_use_value}"
    relevance: "!alcohol_substance_use.isEmpty()  && !alcohol_substance_use.contains('none')"

  - template: "Hypertension diagnosis"
    relevance: "hypertension == 1"

  - template: "Severe hypertension: {bp_systolic_repeat}/{bp_diastolic_repeat} mmHg"
    relevance: "severe_hypertension == 1"

  - template: "Hypertension and symptom of severe pre-eclampsia: {symp_sev_preeclampsia}"
    relevance: "hypertension == 1 && !symp_sev_preeclampsia.isEmpty() && !symp_sev_preeclampsia.contains('none')"

  - template: "Pre-eclampsia diagnosis"
    relevance: "preeclampsia == 1"

  - template: "Severe pre-eclampsia diagnosis"
    relevance: "severe_preeclampsia == 1"

  - template: "Fever: {body_temp_repeat}ºC"
    relevance: "body_temp_repeat >= 38"

  - template: "Abnormal pulse rate: {pulse_rate_repeat}bpm"
    relevance: "pulse_rate_repeat < 60 || pulse_rate_repeat > 100"

  - template: "Anaemia diagnosis"
    relevance: "anaemic == 1"

  - template: "Respiratory distress: {respiratory_exam_abnormal_value}"
    relevance: "!respiratory_exam_abnormal.contains('none') && !respiratory_exam_abnormal.isEmpty()"

  - template: "Low oximetry: {oximetry}%"
    relevance: "oximetry < 92"

  - template: "Abnormal cardiac exam: {cardiac_exam_abnormal_value}"
    relevance: "!cardiac_exam_abnormal.contains('none') && !cardiac_exam_abnormal.isEmpty()"

  - template: "Cervix dilated: {dilation_cm} cm"
    relevance: "dilation_cm > 2"

  - template: "No fetal heartbeat observed"
    relevance: "fetal_heartbeat == 'no'"

  - template: "Abnormal fetal heart rate: {fetal_heart_rate_repeat}bpm"
    relevance: "fetal_heart_rate_repeat < 110 || fetal_heart_rate_repeat > 160"

  - template: "No. of fetuses: {no_of_fetuses}"
    relevance: "no_of_fetuses > 1"

  - template: "Fetal presentation: {fetal_presentation} "
    relevance: "gest_age >= 28 && fetal_presentation == 'transverse'"

  - template: "Amniotic fluid: {amniotic_fluid}"
    relevance: "amniotic_fluid == 'reduced' || amniotic_fluid == 'increased'"

  - template: "Placenta location: {placenta_location_value}"
    relevance: "placenta_location == 'praevia'"

  - template: "HIV risk"
    relevance: "hiv_risk == 1"

  - template: "HIV positive"
    relevance: "hiv_positive == 1"

  - template: "Hepatitis B positive"
    relevance: "hepb_positive == 1"

  - template: "Hepatitis C positive"
    relevance: "hepc_positive == 1"

  - template: "Syphilis positive"
    relevance: "syphilis_positive == 1"

  - template: "Asymptomatic bacteriuria (ASB) diagnosis"
    relevance: "asb_positive == 1"

  - template: "Group B Streptococcus (GBS) diagnosis"
    relevance: "urine_culture == 'positive - group b streptococcus (gbs)'"

  - template: "Gestational Diabetes Mellitus (GDM) diagnosis"
    relevance: "gdm == 1"

  - template: "Diabetes Mellitus (DM) in pregnancy diagnosis"
    relevance: "dm_in_preg == 1"

  - template: "Hematocrit (Ht): {ht}"
    relevance: "ht < 10.5"

  - template: "White blood cell (WBC) count: {wbc}"
    relevance: "wbc > 16000"

  - template: "Platelet count: {platelets}"
    relevance: "platelets < 100000"

  - template: "TB screening positive"
    relevance: "tb_screening_result == 'positive'"
