---
name: total_doses
description: Total Doses
priority: 1
condition: "true"
actions:
  - "total_doses = doses_per_vial * vials_used"
---
name: use_rate
description: The usage of the vacines computed per vaccine (see above vaccines)
priority: 1
condition: "total_doses != 0"
actions:
  - "use_rate = (vaccine_doses_administered / total_doses) * 100"
---
name: pab_total
description: Month to month visual of the total number of children that are protected against tetanus
priority: 1
condition: "true"
actions:
  - "pab_total = new Integer(pab_mother_dt) + new Integer(pab_assisted_delivery) + new Integer(pab_dt_and_assisted_delivery)"
---
name: percentage_first_birth
description: Percentage of women giving birth for the first time ({first_birth} =''yes''
priority: 1
condition: "total_child_births != 0"
actions:
  - "percentage_first_birth = (number_first_birth / total_child_births) * 100"
---
name: percentage_number_rubella_serology
description: Percentage of primapara mother who undertook a rubella serology test
priority: 1
condition: "number_first_birth != 0"
actions:
  - "percentage_number_rubella_serology = (number_rubella_serology / number_first_birth) * 100"
---
name: percentage_serology_results
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "number_rubella_serology != 0"
actions:
  - "percentage_serology_results = (negative_serology_results / number_rubella_serology) * 100"
---
name: percentage_right_measures_6months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_6mnths != 0"
actions:
  - "percentage_right_measures_6months = (right_measures_6months / measures_grp_children_6mnths) * 100"
---
name: percentage_right_measures_12months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_12mnths != 0"
actions:
  - "percentage_right_measures_12months = (right_measures_12months / measures_grp_children_12mnths) * 100"
---
name: percentage_right_measures_18months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_18mnths != 0"
actions:
  - "percentage_right_measures_18months = (right_measures_18months / measures_grp_children_18mnths) * 100"
---
name: percentage_malnutrition_episode_6months
description: Percentage of children 6 months of age with at least 1 ‘previous episode of weight-for-age z-score of -2 or below ( undernutrition).
priority: 1
condition: "malnutrition_episode_percent_grp_children_6mnths != 0"
actions:
  - "percentage_malnutrition_episode_6months = (malnutrition_episode_6months / malnutrition_episode_percent_grp_children_6mnths) * 100"
---
name: percentage_malnutrition_episode_12months
description: Percentage of children with at least 1 ‘previous episode of undernutrition (moderate or severe malnutrition) at 12 months.
priority: 1
condition: "malnutrition_episode_percent_grp_children_12mnths != 0"
actions:
  - "percentage_malnutrition_episode_12months = (malnutrition_episode_12months / malnutrition_episode_percent_grp_children_12mnths) * 100"
---
name: percentage_malnutrition_episode_18months
description: Percentage of children with at least 1 ‘previous episode of undernutrition (moderate or severe malnutrition) at 18 months.
priority: 1
condition: "malnutrition_episode_percent_grp_children_18mnths != 0"
actions:
  - "percentage_malnutrition_episode_18months = (malnutrition_episode_18months / malnutrition_episode_percent_grp_children_18mnths) * 100"
---
name: percentage_mid_mal_6mnths
description: Percentage of children with mild malnutrition at 6 months
priority: 1
condition: "weight_height_count_grp_children_6mnths != 0"
actions:
  - "percentage_mid_mal_6mnths = (mid_mal_grp_children_6mnths / weight_height_count_grp_children_6mnths) * 100"
---
name: percentage_mid_mal_12mnths
description: Percentage of children with mild malnutrition at 12 months
priority: 1
condition: "weight_height_count_grp_children_12mnths != 0"
actions:
  - "percentage_mid_mal_12mnths = (mid_mal_grp_children_12mnths / weight_height_count_grp_children_12mnths) * 100"
---
name: percentage_mid_mal_18mnths
description: Percentage of children with mild malnutrition at 18 months
priority: 1
condition: "weight_height_count_grp_children_18mnths != 0"
actions:
  - "percentage_mid_mal_18mnths = (mid_mal_grp_children_18mnths / weight_height_count_grp_children_18mnths) * 100"
---
name: percentage_mod_mal_6mnths
description: Percentage of chilldren with moderate malnutrition at 6 months
priority: 1
condition: "weight_height_count_grp_children_6mnths != 0"
actions:
  - "percentage_mod_mal_6mnths = (mod_mal_grp_children_6mnths / weight_height_count_grp_children_6mnths) * 100"
---
name: percentage_mod_mal_12mnths
description: Percentage of chilldren with moderate malnutrition at 12 months
priority: 1
condition: "weight_height_count_grp_children_12mnths != 0"
actions:
  - "percentage_mod_mal_12mnths = (mod_mal_grp_children_12mnths / weight_height_count_grp_children_12mnths) * 100"
---
name: percentage_mod_mal_18mnths
description: Percentage of chilldren with moderate malnutrition at 18 months
priority: 1
condition: "weight_height_count_grp_children_18mnths != 0"
actions:
  - "percentage_mod_mal_18mnths = (mod_mal_grp_children_18mnths / weight_height_count_grp_children_18mnths) * 100"
---
name: percentage_sev_mal_6mnths
description: Percentage of children with severe malnutrition at 6 months
priority: 1
condition: "weight_height_count_grp_children_6mnths != 0"
actions:
  - "percentage_sev_mal_6mnths = (sev_mal_grp_children_6mnths / weight_height_count_grp_children_6mnths) * 100"
---
name: percentage_sev_mal_12mnths
description: Percentage of children with severe malnutrition at 12 months
priority: 1
condition: "weight_height_count_grp_children_12mnths != 0"
actions:
  - "percentage_sev_mal_12mnths = (sev_mal_grp_children_12mnths / weight_height_count_grp_children_12mnths) * 100"
---
name: percentage_sev_mal_18mnths
description: Percentage of children with severe malnutrition at 18 months
priority: 1
condition: "weight_height_count_grp_children_18mnths != 0"
actions:
  - "percentage_sev_mal_18mnths = (sev_mal_grp_children_18mnths / weight_height_count_grp_children_18mnths) * 100"
---
name: percentage_obese_grp_6mnths
description: Percentage of obese children at 6 months
priority: 1
condition: "weight_height_count_grp_children_6mnths != 0"
actions:
  - "percentage_obese_grp_6mnths = (obese_grp_children_6mnths / weight_height_count_grp_children_6mnths) * 100"
---
name: percentage_obese_grp_12mnths
description: Percentage of obese children at 12 months
priority: 1
condition: "weight_height_count_grp_children_12mnths != 0"
actions:
  - "percentage_obese_grp_12mnths = (obese_grp_children_12mnths / weight_height_count_grp_children_12mnths) * 100"
---
name: percentage_obese_grp_18mnths
description: Percentage of obese children at 18 months
priority: 1
condition: "weight_height_count_grp_children_18mnths != 0"
actions:
  - "percentage_obese_grp_18mnths = (obese_grp_children_18mnths / weight_height_count_grp_children_18mnths) * 100"