---
name: index_50_total_doses
description: Total Doses
priority: 1
condition: "true"
actions:
  - "index_50_total_doses = index_49_doses_per_vial * index_48_vials_used"
---
name: index_51_use_rate
description: The usage of the vacines computed per vaccine (see above vaccines)
priority: 1
condition: "index_50_total_doses != 0"
actions:
  - "index_51_use_rate = (index_46_vaccine_doses_administered / index_50_total_doses) * 100"
---
name: index_55_PAB_total
description: Month to month visual of the total number of children that are protected against tetanus
priority: 1
condition: "true"
actions:
  - "index_55_PAB_total = new Integer(index_52_PAB_mother_dt) + new Integer(index_53_PAB_assisted_delivery) + new Integer(index_54_PAB_dt_and_assisted_delivery)"