---
name: index_50_total_doses
description: Total Doses
priority: 1
condition: "true"
actions:
  - "index_50_total_doses = index_49_doses_per_vial * index_48_vials_used"
---
name: index_51_use_rate
description: The usage of the vacines computed per vaccine (see above vaccines)
priority: 1
condition: "index_50_total_doses != 0"
actions:
  - "index_51_use_rate = (index_46_vaccine_doses_administered / index_50_total_doses) * 100"
---
name: index_55_PAB_total
description: Month to month visual of the total number of children that are protected against tetanus
priority: 1
condition: "true"
actions:
  - "index_55_PAB_total = new Integer(index_52_PAB_mother_dt) + new Integer(index_53_PAB_assisted_delivery) + new Integer(index_54_PAB_dt_and_assisted_delivery)"
---
name: index_58_percentage_first_birth
description: Percentage of women giving birth for the first time ({first_birth} =''yes''
priority: 1
condition: "index_56_total_child_births != 0"
actions:
  - "index_58_percentage_first_birth = (index_57_number_first_birth / index_56_total_child_births) * 100"
---
name: index_60_percentage_number_rubella_serology
description: Percentage of primapara mother who undertook a rubella serology test
priority: 1
condition: "index_57_number_first_birth != 0"
actions:
  - "index_60_percentage_number_rubella_serology = (index_59_number_rubella_serology / index_57_number_first_birth) * 100"
---
name: index_62_percentage_serology_results
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "index_59_number_rubella_serology != 0"
actions:
  - "index_62_percentage_serology_results = (index_61_negative_serology_results / index_59_number_rubella_serology) * 100"
---
name: index_65_percentage_right_measures_6months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_6mnths != 0"
actions:
  - "index_65_percentage_right_measures_6months = (index_64_right_measures_6months / measures_grp_children_6mnths) * 100"
---
name: index_67_percentage_right_measures_12months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_12mnths != 0"
actions:
  - "index_67_percentage_right_measures_12months = (index_66_right_measures_12months / measures_grp_children_12mnths) * 100"
---
name: index_69_percentage_right_measures_18months
description: Percentage of women who took the serology test that have negative results ({serology_results} = ''negative''
priority: 1
condition: "measures_grp_children_18mnths != 0"
actions:
  - "index_69_percentage_right_measures_18months = (index_68_right_measures_18months / measures_grp_children_18mnths) * 100"